import type { School } from "./types";

// A compact but believable catalog spanning region / size / setting / selectivity
// / price so the matching engine has real signal to work with.
export const SCHOOLS: School[] = [
  {
    id: "ut-austin",
    name: "University of Texas at Austin",
    short: "UT Austin",
    city: "Austin",
    state: "TX",
    region: "Southwest",
    setting: "city",
    size: "large",
    acceptanceRate: 0.29,
    netPrice: 17400,
    strongMajors: ["Computer Science", "Engineering", "Business", "Design"],
    vibe: "Big-city public powerhouse with a huge maker + startup scene.",
    accent: "#bf5700",
    partner: true,
    cpl: 240,
  },
  {
    id: "rice",
    name: "Rice University",
    short: "Rice",
    city: "Houston",
    state: "TX",
    region: "Southwest",
    setting: "city",
    size: "small",
    acceptanceRate: 0.08,
    netPrice: 21900,
    strongMajors: ["Computer Science", "Engineering", "Music", "Biology"],
    vibe: "Small, intense, residential-college culture with great aid.",
    accent: "#00205b",
    partner: true,
    cpl: 320,
  },
  {
    id: "tamu",
    name: "Texas A&M University",
    short: "Texas A&M",
    city: "College Station",
    state: "TX",
    region: "Southwest",
    setting: "suburban",
    size: "large",
    acceptanceRate: 0.63,
    netPrice: 19200,
    strongMajors: ["Engineering", "Computer Science", "Agriculture", "Business"],
    vibe: "Spirited, traditions-rich, enormous engineering pipeline.",
    accent: "#500000",
    partner: true,
    cpl: 180,
  },
  {
    id: "asu",
    name: "Arizona State University",
    short: "ASU",
    city: "Tempe",
    state: "AZ",
    region: "Southwest",
    setting: "city",
    size: "large",
    acceptanceRate: 0.9,
    netPrice: 14300,
    strongMajors: ["Computer Science", "Business", "Journalism", "Design"],
    vibe: "Innovation-first, accessible, massive online + in-person options.",
    accent: "#8c1d40",
    partner: true,
    cpl: 120,
  },
  {
    id: "colorado",
    name: "University of Colorado Boulder",
    short: "CU Boulder",
    city: "Boulder",
    state: "CO",
    region: "West",
    setting: "suburban",
    size: "large",
    acceptanceRate: 0.8,
    netPrice: 20100,
    strongMajors: ["Aerospace", "Computer Science", "Environmental Science"],
    vibe: "Mountains, outdoorsy, strong aerospace + CS.",
    accent: "#cfb87c",
    partner: true,
    cpl: 150,
  },
  {
    id: "gatech",
    name: "Georgia Institute of Technology",
    short: "Georgia Tech",
    city: "Atlanta",
    state: "GA",
    region: "South",
    setting: "city",
    size: "large",
    acceptanceRate: 0.16,
    netPrice: 16800,
    strongMajors: ["Computer Science", "Engineering", "Robotics"],
    vibe: "Top-tier tech, co-op culture, builders everywhere.",
    accent: "#b3a369",
    partner: true,
    cpl: 300,
  },
  {
    id: "uw",
    name: "University of Washington",
    short: "UW",
    city: "Seattle",
    state: "WA",
    region: "West",
    setting: "city",
    size: "large",
    acceptanceRate: 0.48,
    netPrice: 15600,
    strongMajors: ["Computer Science", "Nursing", "Engineering"],
    vibe: "Big-tech adjacent, research heavy, rainy and brilliant.",
    accent: "#4b2e83",
    partner: true,
    cpl: 220,
  },
  {
    id: "olin",
    name: "Olin College of Engineering",
    short: "Olin",
    city: "Needham",
    state: "MA",
    region: "Northeast",
    setting: "suburban",
    size: "small",
    acceptanceRate: 0.16,
    netPrice: 22500,
    strongMajors: ["Engineering", "Computer Science", "Design"],
    vibe: "Tiny, project-based, every class is a build.",
    accent: "#e1483b",
    partner: true,
    cpl: 280,
  },
  {
    id: "rit",
    name: "Rochester Institute of Technology",
    short: "RIT",
    city: "Rochester",
    state: "NY",
    region: "Northeast",
    setting: "suburban",
    size: "large",
    acceptanceRate: 0.71,
    netPrice: 25600,
    strongMajors: ["Computer Science", "Game Design", "Photography", "Engineering"],
    vibe: "Co-op machine, huge for game dev + applied tech.",
    accent: "#f76902",
    partner: true,
    cpl: 160,
  },
  {
    id: "mtu",
    name: "Michigan Technological University",
    short: "Michigan Tech",
    city: "Houghton",
    state: "MI",
    region: "Midwest",
    setting: "rural",
    size: "medium",
    acceptanceRate: 0.74,
    netPrice: 18800,
    strongMajors: ["Engineering", "Computer Science", "Environmental Science"],
    vibe: "Remote, snowy, hands-on engineering with great outcomes.",
    accent: "#000000",
    partner: true,
    cpl: 110,
  },
  {
    id: "spelman",
    name: "Spelman College",
    short: "Spelman",
    city: "Atlanta",
    state: "GA",
    region: "South",
    setting: "city",
    size: "small",
    acceptanceRate: 0.39,
    netPrice: 23400,
    strongMajors: ["Computer Science", "Biology", "Political Science"],
    vibe: "Historic women's college, tight community, rising CS program.",
    accent: "#0b5394",
    partner: true,
    cpl: 200,
  },
  {
    id: "calpoly",
    name: "Cal Poly San Luis Obispo",
    short: "Cal Poly SLO",
    city: "San Luis Obispo",
    state: "CA",
    region: "West",
    setting: "suburban",
    size: "large",
    acceptanceRate: 0.3,
    netPrice: 19900,
    strongMajors: ["Engineering", "Computer Science", "Architecture", "Agriculture"],
    vibe: "Learn-by-doing on the central coast, very employable grads.",
    accent: "#154734",
    partner: true,
    cpl: 210,
  },
  {
    id: "purdue",
    name: "Purdue University",
    short: "Purdue",
    city: "West Lafayette",
    state: "IN",
    region: "Midwest",
    setting: "suburban",
    size: "large",
    acceptanceRate: 0.5,
    netPrice: 13100,
    strongMajors: ["Engineering", "Computer Science", "Aviation", "Agriculture"],
    vibe: "Affordable engineering juggernaut, frozen-tuition promise.",
    accent: "#cfb991",
    partner: true,
    cpl: 170,
  },
  {
    id: "northeastern",
    name: "Northeastern University",
    short: "Northeastern",
    city: "Boston",
    state: "MA",
    region: "Northeast",
    setting: "city",
    size: "large",
    acceptanceRate: 0.07,
    netPrice: 29800,
    strongMajors: ["Computer Science", "Business", "Engineering", "Health"],
    vibe: "Co-op pioneer, work-integrated, very urban.",
    accent: "#c8102e",
    partner: true,
    cpl: 260,
  },
  {
    id: "utah",
    name: "University of Utah",
    short: "Utah",
    city: "Salt Lake City",
    state: "UT",
    region: "West",
    setting: "city",
    size: "large",
    acceptanceRate: 0.79,
    netPrice: 12800,
    strongMajors: ["Biology", "Computer Science", "Nursing", "Engineering"],
    vibe: "Utah's big research university — a hospital and medical school right on campus, mountains out every window.",
    accent: "#be0000",
    partner: true,
    cpl: 190,
  },
  {
    id: "byu",
    name: "Brigham Young University",
    short: "BYU",
    city: "Provo",
    state: "UT",
    region: "West",
    setting: "suburban",
    size: "large",
    acceptanceRate: 0.66,
    netPrice: 13200,
    strongMajors: ["Biology", "Business", "Computer Science", "Engineering"],
    vibe: "Big, affordable, and tight-knit in Provo — known for sending lots of grads on to med and grad school.",
    accent: "#002e5d",
    partner: true,
    cpl: 175,
  },
  {
    id: "uvu",
    name: "Utah Valley University",
    short: "UVU",
    city: "Orem",
    state: "UT",
    region: "West",
    setting: "suburban",
    size: "large",
    acceptanceRate: 1.0,
    netPrice: 9200,
    strongMajors: ["Biology", "Nursing", "Business", "Computer Science"],
    vibe: "Open-admission and the cheapest way to start — easy to bring in AP/concurrent credit, then transfer up if you want.",
    accent: "#275d38",
    partner: true,
    cpl: 120,
  },
];

export const schoolById = (id: string): School | undefined =>
  SCHOOLS.find((s) => s.id === id);
