// AUTO-GENERATED by scripts/fetch-scorecard.mjs — real College Scorecard data,
// cached so the app never depends on the live API for these well-known schools.
// Refresh occasionally: node --env-file=.env.local scripts/fetch-scorecard.mjs
import type { ScorecardSchool } from "./scorecard";

export const SCORECARD_CACHE: ScorecardSchool[] = [
  {
    "name": "Massachusetts Institute of Technology",
    "city": "Cambridge",
    "state": "MA",
    "acceptanceRate": 0.0455,
    "netPrice": 20111,
    "size": 4535,
    "completionRate": 0.9624,
    "medianEarnings": 143372,
    "source": "scorecard"
  },
  {
    "name": "Stanford University",
    "city": "Stanford",
    "state": "CA",
    "acceptanceRate": 0.0361,
    "netPrice": 13807,
    "size": 7554,
    "completionRate": 0.9237,
    "medianEarnings": 124080,
    "source": "scorecard"
  },
  {
    "name": "California Institute of Technology",
    "city": "Pasadena",
    "state": "CA",
    "acceptanceRate": 0.0257,
    "netPrice": 16075,
    "size": 987,
    "completionRate": 0.9376,
    "medianEarnings": 128566,
    "source": "scorecard"
  },
  {
    "name": "Harvard University",
    "city": "Cambridge",
    "state": "MA",
    "acceptanceRate": 0.0365,
    "netPrice": 19066,
    "size": 7601,
    "completionRate": 0.9745,
    "medianEarnings": 101817,
    "source": "scorecard"
  },
  {
    "name": "Princeton University",
    "city": "Princeton",
    "state": "NJ",
    "acceptanceRate": 0.0462,
    "netPrice": 6128,
    "size": 5709,
    "completionRate": 0.9735,
    "medianEarnings": 110066,
    "source": "scorecard"
  },
  {
    "name": "Yale University",
    "city": "New Haven",
    "state": "CT",
    "acceptanceRate": 0.0387,
    "netPrice": 23777,
    "size": 6758,
    "completionRate": 0.9603,
    "medianEarnings": 100533,
    "source": "scorecard"
  },
  {
    "name": "Columbia University in the City of New York",
    "city": "New York",
    "state": "NY",
    "acceptanceRate": 0.0399,
    "netPrice": 21590,
    "size": 8973,
    "completionRate": 0.9554,
    "medianEarnings": 102491,
    "source": "scorecard"
  },
  {
    "name": "University of Pennsylvania",
    "city": "Philadelphia",
    "state": "PA",
    "acceptanceRate": 0.054,
    "netPrice": 28699,
    "size": 10650,
    "completionRate": 0.9668,
    "medianEarnings": 111371,
    "source": "scorecard"
  },
  {
    "name": "Cornell University",
    "city": "Ithaca",
    "state": "NY",
    "acceptanceRate": 0.0876,
    "netPrice": 28690,
    "size": 15995,
    "completionRate": 0.9526,
    "medianEarnings": 104043,
    "source": "scorecard"
  },
  {
    "name": "Brown University",
    "city": "Providence",
    "state": "RI",
    "acceptanceRate": 0.0539,
    "netPrice": 25184,
    "size": 7226,
    "completionRate": 0.957,
    "medianEarnings": 93487,
    "source": "scorecard"
  },
  {
    "name": "Dartmouth College",
    "city": "Hanover",
    "state": "NH",
    "acceptanceRate": 0.054,
    "netPrice": 29519,
    "size": 4541,
    "completionRate": 0.9575,
    "medianEarnings": 97434,
    "source": "scorecard"
  },
  {
    "name": "University of California-Berkeley",
    "city": "Berkeley",
    "state": "CA",
    "acceptanceRate": 0.1098,
    "netPrice": 13481,
    "size": 33068,
    "completionRate": 0.9286,
    "medianEarnings": 92446,
    "source": "scorecard"
  },
  {
    "name": "University of California-Los Angeles",
    "city": "Los Angeles",
    "state": "CA",
    "acceptanceRate": 0.0897,
    "netPrice": 12548,
    "size": 33475,
    "completionRate": 0.9264,
    "medianEarnings": 82511,
    "source": "scorecard"
  },
  {
    "name": "University of California-San Diego",
    "city": "La Jolla",
    "state": "CA",
    "acceptanceRate": 0.2671,
    "netPrice": 12470,
    "size": 34948,
    "completionRate": 0.8677,
    "medianEarnings": 84943,
    "source": "scorecard"
  },
  {
    "name": "University of California-Irvine",
    "city": "Irvine",
    "state": "CA",
    "acceptanceRate": 0.2857,
    "netPrice": 14251,
    "size": 30197,
    "completionRate": 0.8638,
    "medianEarnings": 80735,
    "source": "scorecard"
  },
  {
    "name": "University of Southern California",
    "city": "Los Angeles",
    "state": "CA",
    "acceptanceRate": 0.0981,
    "netPrice": 32740,
    "size": 20443,
    "completionRate": 0.9191,
    "medianEarnings": 92498,
    "source": "scorecard"
  },
  {
    "name": "New York University",
    "city": "New York",
    "state": "NY",
    "acceptanceRate": 0.0923,
    "netPrice": 37050,
    "size": 28663,
    "completionRate": 0.8801,
    "medianEarnings": 82509,
    "source": "scorecard"
  },
  {
    "name": "University of Michigan-Ann Arbor",
    "city": "Ann Arbor",
    "state": "MI",
    "acceptanceRate": 0.1564,
    "netPrice": 13138,
    "size": 34177,
    "completionRate": 0.9321,
    "medianEarnings": 83648,
    "source": "scorecard"
  },
  {
    "name": "University of North Carolina at Chapel Hill",
    "city": "Chapel Hill",
    "state": "NC",
    "acceptanceRate": 0.1534,
    "netPrice": 11655,
    "size": 20752,
    "completionRate": 0.9162,
    "medianEarnings": 72200,
    "source": "scorecard"
  },
  {
    "name": "University of Virginia-Main Campus",
    "city": "Charlottesville",
    "state": "VA",
    "acceptanceRate": 0.1681,
    "netPrice": 21565,
    "size": 17597,
    "completionRate": 0.9545,
    "medianEarnings": 86863,
    "source": "scorecard"
  },
  {
    "name": "Carnegie Mellon University",
    "city": "Pittsburgh",
    "state": "PA",
    "acceptanceRate": 0.1166,
    "netPrice": 31944,
    "size": 7304,
    "completionRate": 0.933,
    "medianEarnings": 114862,
    "source": "scorecard"
  },
  {
    "name": "Johns Hopkins University",
    "city": "Baltimore",
    "state": "MD",
    "acceptanceRate": 0.0644,
    "netPrice": 18809,
    "size": 5693,
    "completionRate": 0.9421,
    "medianEarnings": 87555,
    "source": "scorecard"
  },
  {
    "name": "Duke University",
    "city": "Durham",
    "state": "NC",
    "acceptanceRate": 0.0571,
    "netPrice": 29612,
    "size": 6442,
    "completionRate": 0.963,
    "medianEarnings": 97800,
    "source": "scorecard"
  },
  {
    "name": "Northwestern University",
    "city": "Evanston",
    "state": "IL",
    "acceptanceRate": 0.0769,
    "netPrice": 29167,
    "size": 9201,
    "completionRate": 0.9551,
    "medianEarnings": 89363,
    "source": "scorecard"
  },
  {
    "name": "University of Illinois Urbana-Champaign",
    "city": "Champaign",
    "state": "IL",
    "acceptanceRate": 0.4237,
    "netPrice": 14355,
    "size": 36258,
    "completionRate": 0.8501,
    "medianEarnings": 81054,
    "source": "scorecard"
  },
  {
    "name": "University of Wisconsin-Madison",
    "city": "Madison",
    "state": "WI",
    "acceptanceRate": 0.452,
    "netPrice": 17354,
    "size": 36902,
    "completionRate": 0.8944,
    "medianEarnings": 73792,
    "source": "scorecard"
  },
  {
    "name": "Boston University",
    "city": "Boston",
    "state": "MA",
    "acceptanceRate": 0.1111,
    "netPrice": 24402,
    "size": 18248,
    "completionRate": 0.8931,
    "medianEarnings": 83238,
    "source": "scorecard"
  },
  {
    "name": "Arizona State University Campus Immersion",
    "city": "Tempe",
    "state": "AZ",
    "acceptanceRate": 0.8989,
    "netPrice": 14967,
    "size": 64674,
    "completionRate": 0.6795,
    "medianEarnings": 62668,
    "source": "scorecard"
  },
  {
    "name": "University of Florida",
    "city": "Gainesville",
    "state": "FL",
    "acceptanceRate": 0.242,
    "netPrice": 6541,
    "size": 35629,
    "completionRate": 0.9131,
    "medianEarnings": 71588,
    "source": "scorecard"
  },
  {
    "name": "Ohio State University-Main Campus",
    "city": "Columbus",
    "state": "OH",
    "acceptanceRate": 0.6057,
    "netPrice": 17339,
    "size": 45638,
    "completionRate": 0.8773,
    "medianEarnings": 60409,
    "source": "scorecard"
  },
  {
    "name": "Salt Lake Community College",
    "city": "Salt Lake City",
    "state": "UT",
    "netPrice": 9804,
    "size": 18136,
    "completionRate": 0.2949,
    "medianEarnings": 47867,
    "source": "scorecard"
  },
  {
    "name": "Santa Monica College",
    "city": "Santa Monica",
    "state": "CA",
    "netPrice": 2779,
    "size": 21440,
    "completionRate": 0.3606,
    "medianEarnings": 42193,
    "source": "scorecard"
  },
  {
    "name": "Austin Community College District",
    "city": "Austin",
    "state": "TX",
    "netPrice": 6390,
    "size": 30189,
    "completionRate": 0.1913,
    "medianEarnings": 43177,
    "source": "scorecard"
  }
];
